language: c

sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_6651011d54ed_key -iv $encrypted_6651011d54ed_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
  - docker build -t latexbuild:dockerfile .

script:
  - docker run -d --rm --net='none' -v ${TRAVIS_BRANCH}:/build latexbuild:dockerfile -xelatex -jobname=/build/Dissertation Dissertation.tex
  - ./dropbox_uploader.sh upload Dissertation.pdf ${TRAVIS_BRANCH}/Brandon_Hewer_Dissertation_2018-19-latest.pdf
