language: c

sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_6651011d54ed_key -iv $encrypted_6651011d54ed_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
  - docker build -t latexbuild:dockerfile .

script:
  - docker run -d latexbuild:dockerfile -pdf
